Title: ZOA Charts
Airports:
  Bravo:
    - DEN
  Charlie:
    - COS
  Delta:
    - APA
    - ASE
    - BJC
    - BKF
    - CFO
    - CPR
    - CYS
    - EGE
    - FMN
    - FNL
    - GJT
    - GUR
    - RAP
    - RCA
    - PUB
  Echo:
    - 00C
    - 04V
    - 05V
    - 07V
    - 09K
    - 0H1
    - 0P1
    - 0V7
    - 11V
    - 13R
    - 17V
    - 18V
    - 1F5
    - 1QK
    - 1V0
    - 1V2
    - 1V6
    - 1V8
    - 20V
    - 24N
    - 2V5
    - 2V6
    - 33V
    - 37V
    - 3K3
    - 3K7
    - 3V0
    - 42V
    - 47V
    - 49B
    - 4D9
    - 4V0
    - 4V1
    - 4V6
    - 5K0
    - 5K2
    - 5V4
    - 5V5
    - 5V8
    - 64V
    - 66V
    - 6V0
    - 6V4
    - 76V
    - 7V2
    - 7V5
    - 7V8
    - 7V9
    - 80V
    - 82V
    - 83V
    - 8V6
    - 99V
    - 9V5
    - 9V6
    - 9V7
