Title: ZLC Charts
Airports:
  Bravo:
    - SLC
  Charlie:
    - BOI
    - BIL
  Delta:
    - BZN
    - SUN
    - GPI
    - GTF
    - HLN
    - HIF
    - IDA
    - JAC
    - TWF
    - MSO
    - OGD
    - PIH
    - PVU
  Echo:
    - 00F
    - 00U
    - 05U
    - 06U
    - 10U
    - 1L7
    - 1L9
    - 1S3
    - 1U2
    - 1U7
    - 20U
    - 23S
    - 26U
    - 32S
    - 38S
    - 38U
    - 3U3
    - 3U8
    - 40U
    - 41U
    - 44U
    - 48S
    - 4U6
    - 4U9
    - 52S
    - 5U1
    - 5U5
    - 5U8
    - 69V
    - 6S0
    - 6S1
    - 6S3
    - 6S8
    - 6U7
    - 74V
    - 79S
    - 7S0
    - 7S6
    - 8S0
    - 8S1
    - 8U6
    - 8U8
    - 97M
    - 9D2
    - 9S2
    - 9S5
    - 9U0
    - AFO
    - AOC
    - BAM
    - BCE
    - BHK
    - BKE
    - BMC
    - BNO
    - BPI
    - BTF
    - BTM
    - BWW
    - BYG
    - BYI
    - CDC
    - CII
    - COD
    - CTB
    - D50
    - DIJ
    - DLN
    - DTA
    - DUB
    - EKO
    - EKS
    - ELY
    - EMM
    - ENV
    - EUL
    - EVW
    - FBR
    - FOM
    - GDV
    - GEY
    - GGW
    - GNG
    - HCR
    - HRF
    - HSG
    - HVE
    - HVR
    - HWQ
    - JDN
    - JER
    - LGU
    - LLJ
    - LND
    - LTY
    - LVM
    - LWL
    - LWT
    - M46
    - M75
    - MAN
    - MLD
    - MLF
    - MLS
    - MYL
    - N15
    - OLF
    - ONO
    - PNA
    - PO1
    - POY
    - PUC
    - PWD
    - RED
    - RIF
    - RIW
    - RKS
    - RPX
    - RVF
    - RXE
    - S00
    - S01
    - S09
    - S25
    - S27
    - S34
    - S49
    - S64
    - S69
    - S71
    - S75
    - S78
    - S85
    - S87
    - SBX
    - SDY
    - SHR
    - SMN
    - SPK
    - TMT
    - TVY
    - U01
    - U02
    - U03
    - U05
    - U06
    - U10
    - U12
    - U14
    - U34
    - U36
    - U42
    - U52
    - U55
    - U56
    - U58
    - U68
    - U69
    - U70
    - U76
    - U78
    - U82
    - U89
    - VEL
    - WMC
    - WRL
    - WYS
    - XWA